name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run unit tests
      run: npm run test:unit

    - name: Run UI tests
      run: npm run test:ui

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H 'Accept: application/json' \
        -H 'Authorization: Bearer $RENDER_API_KEY' \
        -H 'Content-Type: application/json' \
        -d '{"serviceId": "<your-service-id>", "clearCache": false}' \
        https://api.render.com/v1/services/<your-service-id>/deploys
