name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Start server
      run: |
        nohup npm start &
        echo $! > server.pid

    - name: Wait for server to be ready
      run: sleep 15

    - name: Run unit tests
      run: npm run test:unit

    - name: Run UI tests
      run: npm run test:ui

    - name: Stop server
      run: |
        if [ -f server.pid ]; then
          kill $(cat server.pid)
        fi

    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H 'Accept: application/json' \
        -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
        -H 'Content-Type: application/json' \
        -d '{"serviceId": "srv-cprurtl6l47c73dsrq1g", "clearCache": false}' \
        https://api.render.com/v1/services/srv-cprurtl6l47c73dsrq1g/deploys
